#!/usr/bin/env node
/**
 * refresh-reviews.js — roll newly-APPROVED customer reviews onto the static product
 * pages by regenerating them. The generators only emit aggregateRating/review schema
 * for products that have real approved reviews, so this is the one command to run after
 * moderating reviews (or on a schedule) to make the stars appear.
 *
 * Flow:
 *   1. Read /api/reviews/summary — the set of products with approved reviews.
 *   2. If none (and not --force), skip the rebuild entirely (no needless page churn).
 *   3. Otherwise regenerate the countertop pages + every marketplace category.
 *   4. With --commit, stage/commit/push the changed pages so a cron can be hands-off.
 *
 * Usage:
 *   node scripts/refresh-reviews.js              # rebuild only if approved reviews exist
 *   node scripts/refresh-reviews.js --force      # rebuild regardless (e.g. price refresh)
 *   node scripts/refresh-reviews.js --commit     # rebuild, then git add/commit/push
 *   npm run refresh-reviews[:commit]
 *
 * Real-reviews-only: this never fabricates ratings — it just re-runs the generators,
 * which read the live approved-reviews API.
 */
const { execFileSync, spawnSync } = require('child_process');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const API = 'https://surprise-granite-email-api.onrender.com';
const args = process.argv.slice(2);
const FORCE = args.includes('--force');
const COMMIT = args.includes('--commit');

// Marketplace categories the generator knows about (see gen-marketplace-pages.js CFG).
const MARKETPLACE_CATS = ['sink', 'faucet', 'tile', 'fixture', 'accessory'];

function fetchSummary() {
  try {
    const raw = execFileSync('curl', ['-s', '-m', '30', `${API}/api/reviews/summary`], { maxBuffer: 1 << 24 }).toString();
    const products = (JSON.parse(raw).products) || {};
    return products;
  } catch (e) {
    console.error(`✗ could not reach the reviews API (${e.message}). Aborting — try again later.`);
    process.exit(1);
  }
}

function run(label, file, extraArgs = []) {
  console.log(`\n── ${label} ─────────────────────────────`);
  const r = spawnSync('node', [path.join('scripts', file), ...extraArgs], { cwd: ROOT, stdio: 'inherit' });
  if (r.status !== 0) { console.error(`✗ ${label} failed (exit ${r.status})`); process.exit(r.status || 1); }
}

// ---- 1. what has approved reviews? ----
const products = fetchSummary();
const reviewedSkus = Object.keys(products).filter((s) => products[s] && products[s].count > 0);
const totalReviews = reviewedSkus.reduce((n, s) => n + products[s].count, 0);
console.log(`Approved reviews: ${totalReviews} across ${reviewedSkus.length} product(s).`);

if (!reviewedSkus.length && !FORCE) {
  console.log('\nNothing to roll onto pages yet — no approved reviews.');
  console.log('Approve some (staff moderation), then re-run. Use --force to rebuild anyway (e.g. to refresh prices).');
  process.exit(0);
}

// ---- 2. regenerate every product surface ----
// (We rebuild all categories: the summary keys by sku/slug but not category, so this is the
//  simplest correct way to guarantee a reviewed product's stars render wherever it lives.)
run('Countertop pages', 'build-countertop-pages.js');
for (const cat of MARKETPLACE_CATS) run(`Marketplace: ${cat}`, 'gen-marketplace-pages.js', [cat]);

// ---- 3. optionally commit + push ----
if (COMMIT) {
  console.log('\n── Commit & push ─────────────────────────');
  const changed = spawnSync('git', ['status', '--porcelain', 'countertops', 'marketplace'], { cwd: ROOT }).stdout.toString().trim();
  if (!changed) {
    console.log('No page changes to commit — pages already up to date.');
  } else {
    const msg = `seo: refresh product-review stars (${totalReviews} approved review${totalReviews === 1 ? '' : 's'}, ${reviewedSkus.length} product${reviewedSkus.length === 1 ? '' : 's'})\n\nAuto-regenerated by refresh-reviews.js — rolls approved reviews onto product\npages. Real-reviews-only.\n\nCo-Authored-By: Claude Opus 4.8 (1M context) <noreply@anthropic.com>`;
    for (const a of [['add', 'countertops', 'marketplace'], ['commit', '-q', '-m', msg], ['push', '-q', 'origin', 'main']]) {
      const r = spawnSync('git', a, { cwd: ROOT, stdio: 'inherit' });
      if (r.status !== 0) { console.error(`✗ git ${a[0]} failed`); process.exit(r.status || 1); }
    }
    console.log('Committed & pushed ✓');
  }
}

console.log('\n✓ Done.' + (COMMIT ? '' : ' Review `git status`, then commit when ready.'));
